# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('survivalEP_rcpp_hello_world', PACKAGE = 'survivalEP')
}

vectorAdd <- function(a, b) {
    .Call('survivalEP_vectorAdd', PACKAGE = 'survivalEP', a, b)
}

vectorAdd2 <- function(a, b) {
    .Call('survivalEP_vectorAdd2', PACKAGE = 'survivalEP', a, b)
}

